### ISSUE TITLE
Dependent on Github(?)

### ISSUE THREAD

**Issue by j0ni** [ratatui-org/ratatui-async-template#13]
I just tried to use this template and I could not move past the question about github organization/username.

Is there some way to not use a github identity that I'm missing? If not, would you consider a patch which removed this dependency? (I've never used `cargo generate` before, but I expect it's well documented)

**Comment by kdheepak** [comment]
You can also type in any GitHub user name and it’ll populate a field in Cargo.toml that you can change manually later. 

but you are right, it shouldn’t be tied to GitHub like that and I’m open to a PR. I can also change this later today.

**Comment by kdheepak** [comment]
I moved all the template questions to a `.rhai` script that there I can programmatically check for more things. 

![out](https://github.com/ratatui-org/ratatui-async-template/assets/1813121/dccf59f1-3548-4409-b542-360dc1a469c4)
