### ISSUE TITLE
Question: How to implement component hierarchy with layout?

### ISSUE THREAD

**Issue by gintsgints** [ratatui-org/ratatui-async-template#15]
I would like to implement components which includes other component. [Like here ](https://github.com/gintsgints/fir/blob/master/src/root.rs).

What would be your recommended way of making it?

**Comment by kdheepak** [comment]
Can you elaborate on what exactly you want to do? 

To implement a `Component` is to implement this trait:

https://github.com/ratatui-org/ratatui-async-template/blob/2db14f5cecbd2ff66e991bc3d97936624be5c6c0/template/src/components.rs#L14-L47

So for components that contain other components, you can implement these methods and forward the functions to the subcomponents, either based on some condition or unconditionally.

The `App` struct (i.e. the root) does this unconditionally (but without implementing the trait):

https://github.com/ratatui-org/ratatui-async-template/blob/2db14f5cecbd2ff66e991bc3d97936624be5c6c0/template/src/app.rs#L50-L60

**Comment by gintsgints** [comment]
So components that contains other components will have same code as app do?:

```rust
    for component in self.components.iter_mut() {
      component.register_action_handler(action_tx.clone())?;
    }

    for component in self.components.iter_mut() {
      component.register_config_handler(self.config.clone())?;
    }

    for component in self.components.iter_mut() {
      component.init(tui.size()?)?;
    }
```

sounds like lot of repeated code :)

**Comment by kdheepak** [comment]
You can make every component a field in `app.components` and then the current template will handle it for you. But if you want to do nested components, my understanding is that you’ll have to manage it yourself. 

fwiw, this is just a template and an example of how to organize your code in the form of components. You can always build exactly what your application needs and break the template’s mold s as you wish. If you wish for something more feature rich and structured, you might want to consider looking into `tui-realm`.

**Comment by kdheepak** [comment]
More specifically, a `Component` is a trait that defines an interface. 
This interface allows any struct that implements the `Component` trait to interact with the main application loop, handle user events, update its state, and render itself within a specified area of the user interface. Here's an updated version with docstrings:

https://github.com/ratatui-org/ratatui-async-template/blob/87904885f0851162b3000abed65e5d3c19238a8c/template/src/components.rs#L14-L123

Out of these methods the following will be rarely used in my opinion:

1. `register_action_handler`: (optional) allows the struct to send `Action` messages on a channel that can be received in the main loop. Only required when you want to send `Action` messages in tokio spawned tasks in a component
2. `register_config_handler`: (optional) allows the struct to use a global configuration. Only required if you want to share the entire configuration with the struct
3. `init`: (optional) this method is called before the main loop begins and allows the struct to perform any initialization steps

The following will need to be implemented if you want interactivity

5. `handle_events`: this method is called when an event is received in the main loop. By default it calls `handle_key_events` and `handle_mouse_events` which are empty default implementation methods in the trait. 

The only two methods that you have to implement are `update` and `draw`:

6. `update`: this method is called with an `Action` and as the implementer of the trait, you are supposed to update the state of the component based on the `Action` message
7. `draw`: this method is called with the frame and the area available and as the implementer, you are supposed to decide how the component should be rendered.

These methods have to be called from _somewhere_. Right now they are called in `app.run()`:

https://github.com/ratatui-org/ratatui-async-template/blob/2db14f5cecbd2ff66e991bc3d97936624be5c6c0/template/src/app.rs#L96-L135

`App` has a field called `components`:

https://github.com/ratatui-org/ratatui-async-template/blob/2db14f5cecbd2ff66e991bc3d97936624be5c6c0/template/src/app.rs#L19

If you populate this `components` field with any number of `Box<dyn Component>` objects, the `app.run()` will call the appropriate methods on them as needed. Here's a very trivial example in the counter app:

https://github.com/ratatui-org/ratatui-async-template/blob/2db14f5cecbd2ff66e991bc3d97936624be5c6c0/ratatui-counter/src/app.rs#L40

So there's no need for nested components if you take advantage of the above feature. If you do still want to have any nested components, then you'll have to manage the `draw` call and `update` calls (at the very least) manually for them. That can be as simple as forwarding the calls to the relevant nested components as needed, or as complex as you need it to be. 

Hope that helps clarify the way you can go about this.

**Comment by gintsgints** [comment]
Ok. All well explained. Thanks.
