### ISSUE TITLE
Git commit hash not appearing in version

### ISSUE THREAD

**Issue by kumo** [ratatui-org/ratatui-async-template#18]
First things first, thanks for this template. I am unable though to get the git commit info to appear in the built app. It appears if I run it via cargo, but once I build it, the information is lost. The same thing happens with the demo counter app.

**Comment by kumo** [comment]
It looks like it is probably due to lazy_static, so I think the problem is not in this template.

**Comment by kdheepak** [comment]
Good catch! I didn't catch that issue since I think my personal projects were using the template before introducing `lazy_static`. I made a fix now.

**Comment by joshka** [comment]
I wonder if you might be able to replace some of this with vergen? (docs: https://docs.rs/vergen/8.2.4/vergen/)

**Comment by kdheepak** [comment]
That does look interesting! I’ll check it out.
