### ISSUE TITLE
Cannot increase counter

### ISSUE THREAD

**Issue by proppp** [ratatui-org/ratatui-async-template#6]
I can't increment/decrement the counter by typing any keys. Even when pressing /, it doesn't enter input mode. The app works (i.e. app ticker increases), but it seems it doesn't receive input, not even Ctrl-C to quit. Any ways to debug this? 
Thanks!

**Comment by kdheepak** [comment]
Can you type `cargo run -- --version`?

```
ratatui-async-template v0.1.0-10-f59c265
```

**Comment by dev-zero** [comment]
Following the nicely written tutorial/book, I stumbled over the configuration.
Creating a `config.toml` with the following content (Help does not exist, example needs to be updated):

```
[keymap]
"q" = "Quit"
"j" = "ScheduleIncrement"
"k" = "ScheduleDecrement"
"/" = "EnterInsert"
"ESC" = "EnterNormal"
"Enter" = "EnterNormal"
"Ctrl-d" = "Quit"
"Ctrl-c" = "Quit"
"Ctrl-z" = "Suspend"
```

and then running with `RATATUI_ASYNC_TEMPLATE_CONFIG=. cargo run` to have the app pick up the config makes it work.

```
ratatui-async-template on  main [?] via 🦀 v1.72.0 ❯ cargo run -- --version
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/ratatui-async-template --version`
ratatui-async-template v0.1.0-6af1fed

Authors: Dheepak Krishnamurthy

Config directory: /Users/$USER/Library/Application Support/com.kdheepak.ratatui-async-template
Data directory: /Users/$User/Library/Application Support/com.kdheepak.ratatui-async-template
```

**Comment by kdheepak** [comment]
Oh my! Good point. 

I think in addition to improving the documentation, I have to make it such that the app works even without a configuration file.

**Comment by kdheepak** [comment]
I've updated the code such that a default keymap will be used if there's no configuration file. I'll update the documentation later today.

Thanks for the error report!

**Comment by proppp** [comment]
That did the trick, thanks to all! ^_^

**Comment by proppp** [comment]
c
